### PR TITLE
Adds alternative solution to 2 of week 6.

### PR DESCRIPTION
**Pull request by nhmacuk**

### CODE REVIEW

**Comment by FrankHeijden** [comment]
This version doesn't seem to work for me;

```
Status: CompilationFailure
----------
1. ERROR at solution.java (at line 21)
	b.add(k);
	^
b cannot be resolved
----------
1 problem (1 error)
```

**Comment by FrankHeijden** [comment]
I strongly suggest to not use such generalised names for variables haha

**Comment by nhmacuk** [comment]
Oh huh that sucks, I'll fix it asap. And I'll try to use more descriptive naming in future commits.

**Comment by nhmacuk** [comment]
I'll create a new pull request with the changed file.

**Comment by nhmacuk** [comment]
gg

**Pull request closed without merging**
